### ISSUE TITLE
Update the binaries listed on the Releases page

### ISSUE THREAD

**Issue by cvan** [KhronosGroup/COLLADA2GLTF#1]
Would it be possible to update the binaries on the [Releases page](https://github.com/KhronosGroup/COLLADA2GLTF/releases)?

([This Wiki page](https://github.com/KhronosGroup/COLLADA2GLTF/wiki#binaries) says to look [there](https://github.com/KhronosGroup/COLLADA2GLTF/releases).)

**Comment by pjcozzi** [comment]
@cvan the glTF 1.0 converter is there at the bottom (we want to flip the order like the old repo so it is at the top).  Are you looking for a build from the latest master for a specific fix?

**Comment by cvan** [comment]
Winfoes trunk and macOS ideally. Thanks

**Comment by strech345** [comment]
i doesn't find any binaries

**Comment by cvan** [comment]
> Are you looking for a build from the latest master for a specific fix?

Yes, I and a couple other folks are looking to test glTF for use in WebGL (WebVR). The only binary listed on the [Releases](https://github.com/KhronosGroup/COLLADA2GLTF/releases) page is from Jan 26. To make it easier, would it be possible to include a more recent Release? I filed #2 for auto-hosting, which can obviously come later.

Thanks for your help 👍

**Comment by pjcozzi** [comment]
@tfili do you have any bandwidth to put new builds up?

**Comment by tfili** [comment]
@pjcozzi I'll try to get to it soon. Maybe early next week.

**Comment by mflux** [comment]
I'm also looking for binaries. 

The releases page is pointed at from:

https://github.com/KhronosGroup/COLLADA2GLTF/wiki

Literally a small link there that says "Download compiled binaries from the Releases page."... follow the link... no binaries.

**Comment by xtassin** [comment]
Same here: could not find binaries anywhere. :(

**Comment by javagl** [comment]
@lexaknyazev drafted a 1.0 release 26 days ago, but the drafts are not publicly visible. Is there any reason to *not* make the latest one public?

**Comment by lexaknyazev** [comment]
That release is much older than 26 days (actually it's from the [old page](https://github.com/KhronosGroup/glTF/releases)).
Afair, plan was to make a new build from current sources and publish it in this repo.

CC @pjcozzi @tfili

**Comment by javagl** [comment]
I wonder whether there is a timeline or roadmap for setting up the build- and deployment infrastructure...? (This actually refers to https://github.com/KhronosGroup/COLLADA2GLTF/issues/2 ...) 

In the meantime, I compiled it locally, for Win64 `*`, and hope that it is OK that I have uploaded this as an **UN**OFFICIAL SNAPSHOT at http://javagl.de/collada2gltf-UNOFFICIAL-SNAPSHOT-2016-11-25-windows_x64.zip - **with no warranties whatsoever.**  

(The libraries are linked statically, so in addition to the [LICENSE.md](https://github.com/KhronosGroup/COLLADA2GLTF/blob/master/LICENSE.md), I'll at least add a pointer to the [zlib license](http://www.zlib.net/zlib_license.html) and [libpng license](http://www.libpng.org/pub/png/src/libpng-LICENSE.txt) here. The only dependencies are the MSVC DLLs, that are also included. I think it should be possible to also link them statically. At least I once did this for another library, based on a [CMake FAQ entry](https://cmake.org/Wiki/CMake_FAQ#How_can_I_build_my_MSVC_application_with_a_static_runtime.3F) )

---

`*` I wanted to try this, mainly because I thought that the warning
> "libpng or one of its dependencies couldn't be found. Transparency may not be correctly detected."

that is printed when libpng is missing might be related to an issue that I've recently been struggling with - but it wasn't: Even with libpng, some textures that are supposed to be transparent are rendered in opaque black.

**Comment by lasalvavida** [comment]
Just for the record, I'm going to cc #2. I do have a 1.0-release tag on my fork: https://github.com/lasalvavida/COLLADA2GLTF/releases/tag/1.0-release with compiled binaries for windows and linux generated from CI for those who are looking for them.

**Comment by lasalvavida** [comment]
Release binaries are now built off of tags
