### ISSUE TITLE
Support for transparency maps

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#121]
See https://github.com/KhronosGroup/glTF/issues/530 by @AndreyOrlov

**Comment by lasalvavida** [comment]
Some notes from #218 - the model here does not actually contain transparency maps - just transparency color elements that we can easily support.

It is technically possible that a COLLADA model could specify a transparency texture map - but I haven't seen one in the wild.

For now I am just going to emit a warning to stderr if we see one of these since there really isn't a clear and easy way to integrate it.

I think the best thing to do if we could would be to multiply the transparency map into the baseColorTexture. This would require some image processing that is a bit out of scope for the project at the moment though.

Even if we could do it, this gets messy pretty quickly.

* What do COLLADA transparency map images look like? Are they single channel? If we get one that has more than one channel, what should we do?

* What if there is no baseColorTexture to multiply it into? Should we fill the texture with some constant color? What color?

* Probably the absolute worst: what if we have a baseColorTexture and a transparency map, but they have different texture coordinate sets?

I am going to close this when #218 merges since the model from the original issue does convert correctly with the current transparency implementation and the kind of image processing that would be required to add support for transparent textures is out of scope for now.

Happy to revisit this if we decide that image processing is something we want to do in this project which could also potentially enable supporting conversion from texture formats that glTF doesn't support in the future.
