### ISSUE TITLE
this asset probably refers to invalid image Ids within

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#129]
Replaces https://github.com/KhronosGroup/glTF/issues/800 by @xuncanzhe

---

>The error message occurs during the conversion. "Inconsistency error: this asset probably refers to invalid image Ids within <surface>". I can use other software to open the dae file. Could you help me determine the cause of the problem? convert tool or dae file. No exception hint when compiling the [tool.（centos7）
>
>OneDrive file url: https://1drv.ms/u/s!AkXxHoUK23z6hOUF90HpSuQm76K-Vg

---

Is this invalid COLLADA that the other loaders are just working around?

**Comment by xuncanzhe** [comment]
yes, This data is convert from osgb using OpenSceneGraph tool. It can be displayed in Bitmanagement。

**Comment by lasalvavida** [comment]
I believe this is actually a bug in OpenCOLLADA. The image is declared inside of the `profile_COMMON` tag instead of `library_images`, but that should still be valid:

![image](https://user-images.githubusercontent.com/2489570/39103172-3669d8e4-4677-11e8-9e43-4c7a6b7955dd.png)

The new converter doesn't crash on this, just exports it without the texture. If you put it where OpenCOLLADA expects, it comes out properly:

![image](https://user-images.githubusercontent.com/2489570/39103206-58f95f6a-4677-11e8-88bf-367c8f009b0d.png)

OpenCOLLADA should call `writeImage()` on our writer for the texture image, but that never happens.

**Comment by lasalvavida** [comment]
Opened an issue in OpenCOLLADA: https://github.com/KhronosGroup/OpenCOLLADA/issues/571

This can be closed once this gets fixed on their end and that gets merged in here.

**Comment by lasalvavida** [comment]
I have an open pull request in OpenCOLLADA for this issue: https://github.com/KhronosGroup/OpenCOLLADA/pull/578
