### ISSUE TITLE
Why the gltf2.0 model is darker than the gltf1.0?

### ISSUE THREAD

**Issue by Frank-Chan** [KhronosGroup/COLLADA2GLTF#172]
Hi Everyone,
        I use the following command-line tool to convert dae file to glTF 2.0.
`E:\colla\collada2gltf2.1.1>collada2gltf-bin.exe -i E:\daexiangmihujiedao\4403040070061000002_17.dae -o E:\test\dae2gltf\gltf2.gltf`
       And the following  command-line tool to convert dae file to glTF 1.0.
`E:\colla\collada2gltf2.1.1>collada2gltf-bin.exe -i E:\daexiangmihujiedao\4403040070061000002_17.dae -o E:\test\dae2gltf\gltf1.gltf -v 1.0`

The gltf1.0 and 2.0 file display in the Cesium are as follows
![gltf](https://user-images.githubusercontent.com/8639688/38490217-14cba66a-3c1b-11e8-96a1-9ca82952a298.png)
                 Fig.1 gltf1.0 result
![gltf2](https://user-images.githubusercontent.com/8639688/38490250-2cd0f094-3c1b-11e8-80cc-c9adefe79b4f.png)
                 Fig.2 gltf2.0 result
As you can see above, the gltf2.0 file is much darker than the 1.0 one. **What's wrong with my command-line ? What should I do to highlight the gltf2.0 file or lighting the model?** @lasalvavida @lilleyse
     I uploaded my gltf files converted by the above commad-line.
[gltffiles.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/1889283/gltffiles.zip)

Best Regards,
Frank-Chan

**Comment by emackey** [comment]
I have a lighting fix in the works for Cesium, see https://github.com/AnalyticalGraphicsInc/cesium/pull/6430

**Comment by emackey** [comment]
Actually your model has a ton of validation errors, are you sure you're using the correct version of the COLLADA2GLTF tool?  It doesn't look up to date.

**Comment by lasalvavida** [comment]
@emackey, it looks like the validation errors are from the generated BINORMAL and TANGENT semantics/accessors. The TANGENT accessors should be vec4, so that does need to fixed. It looks like BINORMAL isn't a valid semantic in 2.0? 

@Frank-Chan, could you upload your COLLADA model? 2.0 materials are a lossy mapping since COLLADA materials aren't PBR which may explain the color difference, but I'd like to look into it more if you could provide your model.

**Comment by emackey** [comment]
@lasalvavida Correct, BINORMAL was a common misnomer anyway and should have been called BITANGENT, but no matter, it was removed from the spec and engines calculate it by crossing the TANGENT and NORMAL vectors, and then multiplying by TANGENT.w.

The TANGENT vectors have a 4th component that indicates handedness now.  This component will always be 1.0 or -1.0, and can  be used to flip the tbn matrix.  In practice, the only use case I'm aware of so far happens when model geometry is intentionally mirrored and then flipped (in the modeling tool), resulting in polygons in UV space that wind clockwise instead of counter-clockwise or vice versa.  This causes all the indentations to become bumps and vice-versa.

This first came to light (for me) on our DamagedHelmet model, which does not supply tangents, but only half of the helmet has textures.  The other half is a mirror of the original geometry, with the normals flipped right-side-out.  This means its normal map on the one half is essentially inside-out, with bumps becoming indentations.  Later I made a test model "NormalTangentMirrorTest" that has some intentionally mirrored geometry in it, and indeed the tangents (as exported by the Blender exporter) show -1.0 values on the mirrored vertices.

**Comment by lasalvavida** [comment]
@Frank-Chan, looking briefly add your outputted glTF, if I had to guess I'd say the difference is due to the use of lights in your COLLADA model. glTF 1.0 had lights, but they were removed as part of 2.0 since it doesn't really make sense for lights to be part of your model; they should be part of your renderer/scene, the model should just be geometry and materials. 

If you really need to use glTF 2.0 with lights, you can try converting your model with `-k`, or `--glsl` to use the `KHR_materials_common` and `KHR_technique_webgl` extensions respectively.

:warning: Please note, that these extensions are experimental and are not fully drafted yet. As such, they may not work on any particular loader and generally I would discourage using them with glTF 2.0 until they are completed.

**Comment by donmccurdy** [comment]
> ...use the `KHR_materials_common` and `KHR_technique_webgl` extensions respectively.

`KHR_materials_common` is not being updated to glTF 2.0, and is not implemented in any engines. There will be a separate [`KHR_lights` extension](https://github.com/KhronosGroup/glTF/pull/1223) for lighting instead.

**Comment by lasalvavida** [comment]
> KHR_materials_common is not being updated to glTF 2.0, and is not implemented in any engines.

That actually isn't true. A glTF 2.0 model with 1.0 materials common should work in Cesium since 1.0 models are mapped to 2.0 in order to display them. This is not really a reliable solution, hence the warning.

> There will be a separate KHR_lights extension for lighting instead.

I am aware of that, but since none of these things are ready, I was simply offering a workaround for what @Frank-Chan can do if needs something that works right now.

**Comment by donmccurdy** [comment]
Ah I see — thanks for clarifying. Yes `KHR_lights` is not useable yet so your advice makes sense.

**Comment by Frank-Chan** [comment]
@lasalvavida This is my COLLADA model which is converted from 3dsMax.
[daeghds.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/1892598/daeghds.zip)

**Comment by Frank-Chan** [comment]
> If you really need to use glTF 2.0 with lights, you can try converting your model with -k, or --glsl to use the KHR_materials_common and KHR_technique_webgl extensions respectively.

@lasalvavida There are no _-k_ options in the command-line. 
![collada2gltf](https://user-images.githubusercontent.com/8639688/38535547-8f31ac4c-3cb6-11e8-9513-d2429be8a668.png)
And I tried the command-line with _--glsl_, but the gltf model is lost textures in Cesium.
![collada2gltf-g](https://user-images.githubusercontent.com/8639688/38535545-8ee56b3e-3cb6-11e8-8316-3bbb6ca08605.png)
![gltfk](https://user-images.githubusercontent.com/8639688/38535386-c9977714-3cb5-11e8-819b-d9c72614a41c.png)

**Comment by lasalvavida** [comment]
> @lasalvavida There are no -k options in the command-line.

My apologies, it's `-m`. It was `-k` in the legacy converter.

> And I tried the command-line with --glsl, but the gltf model is lost textures in Cesium.

It would appear that Cesium doesn't support `KHR_technique_webgl` yet and so your model is displayed with the default material. I did warn you that trying to do this with glTF 2.0 may or may not work.

Is there a reason you can't use glTF 1.0 for now, or edit your materials so they look the way you want in unlit conditions for glTF 2.0?

Just to be clear this isn't a bug, the converter is behaving as expected.

**Comment by lasalvavida** [comment]
This question has been answered, and #174 and #175 address what needs to be fixed on the converter side. Closing. @Frank-Chan, feel free to re-open if you have any more questions.

**Comment by Frank-Chan** [comment]
Thanks a lot. Just want keep the models update to date.

**Comment by lasalvavida** [comment]
@Frank-Chan, understandable. It looks like @emackey's Cesium lighting changes which just merged in https://github.com/AnalyticalGraphicsInc/cesium/pull/6430 help with this substantially.

![image](https://user-images.githubusercontent.com/2489570/39368461-9cfcbd04-4a07-11e8-9a06-fbe67b3e3e15.png)

**Comment by emackey** [comment]
Thanks for posting this model BTW, in addition to helping test the lighting it also helped us track down a bounding sphere issue that could have otherwise been introduced to Cesium this month.

**Comment by Frank-Chan** [comment]
Thanks for your contribution.  Yesterday, I downloaded your pbr-lighting branch, and copyed the _Build file folder_ from Ceium V1.44 to your code, but the model is still darker. I'm not sure is this  the right operation. @emackey 
![qq 20180428102841](https://user-images.githubusercontent.com/8639688/39390985-5b81bf96-4acf-11e8-9373-cd8abcaa1ab5.jpg)
Fortunately, I find that your pbr-lighting branch has been merged into Cesium master in this morning. Is that mean the 3D tiles model which converted from glTF2.0 will have a brighter lingting just like the picture _lasalvavida_  posted above in the coming new version of [Cesium V1.45]?(https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md#fixes-wrench)

**Comment by emackey** [comment]
@Frank-Chan Yes, in Cesium v1.45, the model should look like what @lasalvavida posted [above](https://github.com/KhronosGroup/COLLADA2GLTF/issues/172#issuecomment-384991346).

One caveat I'll point out is that Cesium makes users specify an actual location on the Earth to place the model, and an actual simulation date & time (that defaults to the browser's idea of "now").  If you've placed the model someplace on the planet and then try to view it while that place is in local nighttime, you won't get as much light on the model.  In fact there's another change yet to come that makes this night much darker (as currently the models are lit from below, as if the Sun can shine up through the ground, but that light will eventually be turned off).

**Comment by Frank-Chan** [comment]
Thanks! @emackey
I tried Cesium v1.45, the glTF2.0 model looks a little daker than the glTF1.0, but much brighter than the old Cesium version.

**Comment by emackey** [comment]
Yep.  The glTF 1.0 version was un-lit, so the textures are shown at maximum brightness at all times.  The 2.0 version has lighting calculations going on, which makes it a little darker during the day and much darker at night.  Try running the Cesium clock fast-forward and back to see the day/night difference.

Keep an eye out for (planned) upcoming Cesium support of [KHR_materials_unlit](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_unlit/README.md) to turn off all the glTF 2.0 lighting, which should make the textures max out like your 1.0 model.
