### ISSUE TITLE
Missing DLL error for 2.1.3

### ISSUE THREAD

**Issue by apptaro** [KhronosGroup/COLLADA2GLTF#195]
COLLADA2GLTF 2.1.3 for windows x64 does not work with missing dll errors:
- VCRUNTIME140D.dll
- ucrtbased.dll
- MSVCP140D.dll

The following have this issue:
- COLLADA2GLTF-v2.1.3-windows-Debug-x64.zip
- COLLADA2GLTF-master-windows-Debug-x64.zip

The following does not have this issue:
- COLLADA2GLTF-v2.1.2-windows-Debug-x64.zip
- COLLADA2GLTF-v2.1.2-windows-Release-x64.zip

**Comment by lasalvavida** [comment]
It looks like something weird happened with the Appveyor build for v2.1.3 (the 32-bit job failed for example). Not a compile failure so something wrong on their end. I'll re-push the tag and we'll see if that fixes it.

**Comment by lasalvavida** [comment]
With that being said, these are Windows system libraries and not something that gets bundled with COLLADA2GLTF. If it still doesn't work on your system after the builds finish, you may need to do a windows update or manually install the latest MSVC++ redistributable.

**Comment by apptaro** [comment]
@lasalvavida Hi, thank you for your quick response. Now I see new v2.1.3 release, but no windows version there. Did something go wrong in the building process?

**Comment by lasalvavida** [comment]
@apptaro, sorry still in the process of fixing this; I'll update this issue once it's done

**Comment by cx20** [comment]
@apptaro If the release version of VC++ runtime is required, it can be downloaded from the following.
https://www.microsoft.com/en-US/download/details.aspx?id=53587

@lasalvavida If my remember is correct, I think that we can not redistribute the debug version of the application created with VC++.

https://msdn.microsoft.com/en-us/library/aa985618.aspx

> Debug versions of an application are not redistributable, and debug versions of the Visual C++ library DLLs are not redistributable.

**Comment by lasalvavida** [comment]
> debug versions of the Visual C++ library DLLs are not redistributable.

And we don't distribute it; you have to have the associate runtime libraries installed to use debug builds.

We distribute debug versions so that you can use the COLLADA2GLTF or GLTF libraries as standalone pre-compiled libraries with debugging symbols for development. The debug executable binary isn't really meant to be used.

> Debug versions of an application are not redistributable

I wasn't aware of this; it sounds like this is a legal, not a technical restriction. I'm surprised that Appveyor allows debug artifacts at all if this is the case. I'll need to look into it a bit more, but we can certainly take down the debug artifacts and take debug builds out of CI.

**Comment by lasalvavida** [comment]
v2.1.3 Release is up

**Comment by apptaro** [comment]
@lasalvavida Thank you, COLLADA2GLTF-v2.1.3-windows-Release-x64.zip worked without installing other things. So I will close this issue, but have logged another regression issue #200 for 2.1.3.
