### ISSUE TITLE
Whole GLTF object tree is leaked

### ISSUE THREAD

**Issue by tfili** [KhronosGroup/COLLADA2GLTF#229]
Probably not the end of the world if the converter is used as a single run executable, but if COLLADA2GLTF is used as a library, every conversion will leak the entire hierarchy of objects. `COLLADA2GLTF::Writer` doesn't have a destructor so all the pointers it stores in `map`s and `vector`s never get cleaned up. This will become a disaster very quickly.

I initially noticed it is because I converted 2 models that use the same texture. Since the `GLTF::Image` objects are never destroyed, they remain in the `_imageCache` between conversions. When the second model uses the cached image, the model ends up without an image, because it assumes if an image is in the cache it is already in the model, but it is from the previous model.

**Comment by tfili** [comment]
Maybe the best solution here is to just use `std::shared_ptr` for all `GLTF::*` objects.

**Comment by Ziriax** [comment]
Yes, our Maya2glTF exporter that uses this GLTF library manages the lifetime of all these objects manually. 

That is fine as far as the GLTF library never creates any objects, then one could say that the library has "weak" pointers to externally allocated objects.

But we discovered that calling packAccessors creates a lot of new accessors, buffer-views and buffers... For now we copy pasted that code to adjust it.

They easiest pattern might be a factory to keep track of all the created objects, but indeed using shared_ptr or even unique_ptr would help a lot.

**Comment by lasalvavida** [comment]
> Since the GLTF::Image objects are never destroyed, they remain in the _imageCache between conversions.

@tfili, right now the onus is on the library consumer to free the generated GLTF object tree when they are done with it. This is the way that @Ziriax has been using the GLTF sub-library in Maya2GLTF from what I understand. #152 removes the image from the cache when it is destroyed, so as long as you delete the image objects, this will not be the case.

> Maybe the best solution here is to just use std::shared_ptr for all GLTF::* objects.

My only hesitation with "smart" pointers is that I typically don't see other libraries expose them as part of their API. It seems like they either stick with pass by value or expose raw pointers giving the library user the option to wrap the result in smart pointers if they so choose, but not forcing them to do so.

This could also just be because the libraries were written before smart pointers made it into the STL, but most "modern" c++ libraries that I've seen don't do this either.

> But we discovered that calling packAccessors creates a lot of new accessors, buffer-views and buffers... For now we copy pasted that code to adjust it.

I think the issue here is less that it makes new accessors, etc. and more that it doesn't do a very good job of cleaning up the old ones.

The solution here is probably to have a good set of destructors for cleaning up the tree and to make sure that optimization functions clean up any objects they orphan.

I think as long as the destructor of the root `GLTF::Asset` correctly frees the rest of the tree, you could wrap it in whatever smart pointer fits your needs as a consumer of the library. However, if there's a good argument for using a particular smart pointer internally I could probably be convinced to go that way instead.

**Comment by Ziriax** [comment]
Nice feedback. 

Regarding smart pointers in C++, according to [this stackoverflow](https://stackoverflow.com/questions/22755469/smart-pointers-in-c-apis) discussion, smart pointers should not be used in C++ APIs when binary files are distributed to be used between different compilers. 

But I guess this is not the case for the GLTF library, it is not used as a binary DLL between compilers.

In that case, the modern C++ guideline [seem to promote smart pointers](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i11-never-transfer-ownership-by-a-raw-pointer-t-or-reference-t)

**Comment by tfili** [comment]
Ok, sounds good @lasalvavida. I've started an experimental branch to see where it goes. I'll open a PR when I get it done.

**Comment by Ziriax** [comment]
@tfili If you add destructors that automatically delete the complete hierarchy, you might also want to make the `GLTF::Object` destructor virtual (although strictly speaking this is not required since GLTF doesn't have any polymorphic objects, but the C++ code does, so it feels like good practice to do so)

This change will break Maya2glTF, but that's okay, it will simplify my code. The COLLADA GLTF library was never intended to be re-used in other projects, so I can live with it :-) I should switch to https://github.com/Microsoft/glTF-SDK, but I didn't find the time for that yet.

**Comment by lasalvavida** [comment]
Fixed in #230.
