### ISSUE TITLE
Is there any triangulation simplification technique used with Draco? 

### ISSUE THREAD

**Issue by liaoweiqi1997** [KhronosGroup/COLLADA2GLTF#233]
Draco is really powerful, but I was wondering if you could add triangulation simplification to it?

**Comment by lasalvavida** [comment]
You can check out the work in progress #215 for using earcut to triangulate polylist/polygons.

There are some issues with skinning still which is why it hasn't been merged yet.

Eventually this will be used on all geometry types to, for example, remove degenerate triangles during conversion.

If you are referring to something like mesh decimation, that is pretty far outside the scope of this project.

**Comment by liaoweiqi1997** [comment]
This does not seem to be enough to reduce the triangulation of the model.

**Comment by liaoweiqi1997** [comment]
Is Draco compression a technique for combining objects of the same type but in different positions?

**Comment by lasalvavida** [comment]
> This does not seem to be enough to reduce the triangulation of the model.

This would only optimize out degenerate triangles. It sounds like you are after mesh simplification/decimation. That is not something I have any plan to support here. It's better done in your 3D editor before exporting or in post-processing.

> Is Draco compression a technique for combining objects of the same type but in different positions?

I do not know, you should ask the folks who write Draco.

**Comment by liaoweiqi1997** [comment]
I mean to find that one chair and three chairs share the same set of materials, which seems not to have been done before.Have you changed anything?
