### ISSUE TITLE
COLLADA2GLTF produces unused empty nodes

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/COLLADA2GLTF#44]
E.g., [glTF/2CylinderEngine.gltf#L1706](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/2CylinderEngine/glTF/2CylinderEngine.gltf#L1706).

See other cases here:
https://travis-ci.org/KhronosGroup/glTF-Sample-Models/builds/235813517#L191

**Comment by lasalvavida** [comment]
These are nodes to which COLLADA has assigned lights, so they aren't considered to be unused. However exporting PBR does not currently reference lights, so they appear as unused empty nodes.

For now I will consider light nodes unused for PBR so that they are optimized out until the KHR_lights extension is further along.

**Comment by lexaknyazev** [comment]
Current validation rule is to consider a node to be empty if it has none of:
- `children`
- `mesh`
- `camera`
- `extensions`
- `extras`
and it's not referred by `skin.joints`.

**Comment by lasalvavida** [comment]
Fixed in #47
