### ISSUE TITLE
Lost texture

### ISSUE THREAD

**Issue by Reon90** [KhronosGroup/COLLADA2GLTF#45]
```xml
<effect id="clouds-effect">
      <profile_COMMON>
        <newparam sid="cloudsgrass_mask-surface">
          <surface type="2D">
            <init_from>cloudsgrass_mask</init_from>
          </surface>
        </newparam>
        <newparam sid="cloudsgrass_mask-sampler">
          <sampler2D>
            <source>cloudsgrass_mask-surface</source>
          </sampler2D>
        </newparam>
        <technique sid="common">
          <lambert>
            <emission>
              <color sid="emission">0 0 0 1</color>
            </emission>
            <ambient>
              <color sid="ambient">0 0 0 1</color>
            </ambient>
            <diffuse>
              <color sid="diffuse">0.8 0.8 0.8 1</color>
            </diffuse>
            <transparent opaque="A_ONE">
              <texture texture="cloudsgrass_mask-sampler"/>
            </transparent>
            <index_of_refraction>
              <float sid="index_of_refraction">1</float>
            </index_of_refraction>
          </lambert>
        </technique>
      </profile_COMMON>
    </effect>
```
converted to
```json
"clouds-effect": {
            "name": "clouds",
            "technique": "technique1",
            "values": {
                "ambient": [
                    0,
                    0,
                    0,
                    1
                ],
                "diffuse": [
                    0.8,
                    0.8,
                    0.8,
                    1
                ],
                "emission": [
                    0,
                    0,
                    0,
                    1
                ]
            }
        }
```
There is no transparent property with texture.

**Comment by lasalvavida** [comment]
See my comment here: https://github.com/KhronosGroup/COLLADA2GLTF/issues/121#issuecomment-441763367

glTF 2.0 PBR doesn't have a concept of a transparency texture, and [KHR_materials_common](https://github.com/KhronosGroup/glTF/tree/master/extensions/1.0/Khronos/KHR_materials_common) for 1.0 doesn't either.

We could technically do this in the shader generation, but that would only work for 1.0 models.

This would require image processing to support properly that is out of the scope of this project for the time being at least. A message is printed now in this case so that you are at least notified that the texture will be omitted.

**Comment by emackey** [comment]
glTF 2.0 PBR can do alpha masking and alpha blending via the base color (texture/factor)'s alpha channel, paired with a material setting.

**Comment by lasalvavida** [comment]
Maybe I wasn't as clear as I could have been.

I'm not saying that glTF 2.0 PBR doesn't support transparent textures.

I'm saying that there is no 1:1 property mapping for a COLLADA `transparent` image map/mask like the one given in this example for glTF materials.

Image processing would be required to combine/modify these textures into something usable which is currently out of scope for this project.
