### ISSUE TITLE
Converter de-indexes triangles

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/COLLADA2GLTF#9]
As stated in the title. I have attached a zip file containing the source model, and the output from collada2gltf. The input has 8 triangles sharing 6 vertices and 5 normals, whereas the output has the same 8 tris with 24 vertices and 24 normals. Clearly this is sub-optimal.

[nameplate.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/635350/nameplate.zip)

I'm going to attempt to dig into this myself, but it's gonna be a lengthy process to adequately understand the code. Any help the original developers can provide would be appreciated.

**Comment by javagl** [comment]
(Disclaimer: I'm not a COLLADA(2GLTF) expert) 

As far as I see, this is only the result of converting the multi-indexed input into the single-indexed output.

COLLADA (as well as OBJ and others) supports the multi-indexed format, where the indices are given *independently* for each attribute. For example, you could have a triangle with vertex Positions and Normals, and the indices for this triangle could be

     P N   P N   P N
     0 0   1 0   2 0

The vertex Position indices are (0,1,2), and the Normal indices are (0,0,0) (i.e. using the same normal for all vertices)

This multi-indexed format is not really supported by OpenGL or WebGL. For rendering, you need a *single* index buffer, which is used for all attributes. So for the example above, you would need **three** normals (even if they are all equal), because they have to be accessed with the same indices as the positions (namely, (0,1,2)). 

Converting from multi-indexed to single-indexed is no rocket science, but may be a bit fiddly when you want to do it efficiently. You have to detect the cases where you have to "duplicate" a vertex, because it is used by two triangles but has different attributes. Fortunately, COLLADA2GLTF is obviously already doing this. And fortunately, this is the only indexing scheme that is supported by glTF, because otherwise, every loader/renderer would have to solve this again. (There are many OBJ loaders out there that get it wrong...)

For more information, see "Filling the index buffer" at http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-9-vbo-indexing/ , or http://stackoverflow.com/questions/11148567/rendering-meshes-with-multiple-indices , or search for things like `multi-indexed single-indexed opengl`

**Comment by lexaknyazev** [comment]
Since that particular example has only 18 unique position/normal combinations, model is definitely sub-optimal.

@pjcozzi @lasalvavida
Should this optimization be a part of collada2gltf processing or it would better to have it as gltf-pipeline stage?

**Comment by lasalvavida** [comment]
I am aware of this and it is fixed in my `converter1.1` branch which guts the old mesh conversion code. @stevenvergenz if you want to work on this in the existing code base in the meantime, you are looking for `converter/meshConverter.cpp`.

**Comment by lasalvavida** [comment]
> Should this optimization be a part of collada2gltf processing or it would be better to have it as gltf-pipeline stage?

gltf-pipeline actually does this already. The `converter1.1` implementation is based off of how this is done there.

**Comment by stevenvergenz** [comment]
Oh interesting, it does? What flag in the gltf pipeline indexes geometry? Or is it automatic?

**Comment by stevenvergenz** [comment]
Incidentally, the [gltf pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline) project should probably be linked in the readme, since everything else glTF-related seems to be

**Comment by lasalvavida** [comment]
> Oh interesting, it does? What flag in the gltf pipeline indexes geometry? Or is it automatic?

It's automatic

**Comment by lasalvavida** [comment]
I am going to close this feature is in the 2.0 converter, and there are no plans to add it to the old converter.
